import "react-notifications/lib/notifications.css"
import "@/app/globals.css"
import SessionProvider from "@/components/SessionProviders"
import { Providers } from "@/components/NextUiProviders"

import { getServerSession } from "next-auth"
export const metadata = {
    title: "Next.js",
    description: "Generated by Next.js",
}
export default async function RootLayout({ children }) {
    const session = await getServerSession()

    return (
        <html lang="en">
            <body>
                <SessionProvider session={session}>
                    <Providers>{children}</Providers>
                </SessionProvider>
            </body>
        </html>
    )
}
